// Definições curtas dos termos técnicos (usadas nos tooltips ⓘ premium).
export const GLOSSARY: Record<string, string> = {
  fng: "Índice de Medo & Ganância (0–100). Medo extremo costuma marcar fundos; ganância extrema, topos. É sentimento do mercado, não preço.",
  fundingCex: "Funding rate dos perpétuos (agregado de várias exchanges). Positivo = comprados pagando vendidos (otimismo em excesso); negativo = vendidos pagando.",
  fundingOnchain: "Funding dos perpétuos on-chain (DEX). Mesma ideia do funding de CEX, mas no mercado descentralizado — bom pra comparar varejo CEX × DeFi.",
  cvd: "CVD (Cumulative Volume Delta): saldo entre compra e venda agressora (a mercado). Subindo = compradores no comando; caindo = vendedores.",
  bookImbalance: "Pressão do book: soma das ordens LIMITE paradas perto do preço (bid = compra, ask = venda), nas faixas ±0,5% e ±2%. Mais bid = book comprador (suporte); mais ask = vendedor (resistência). Diferente do CVD (negócio já executado): aqui é liquidez esperando — e pode ser puxada (spoof). A leitura forte é cruzar com o CVD: book comprador + CVD subindo = pressão real; em direções opostas, desconfie.",
  longShort: "Long/Short ratio: proporção de posições compradas vs vendidas. Muito acima de 1 = excesso de comprados (risco de squeeze de baixa) e vice-versa.",
  squeezeRisk: "Risco de squeeze: cruza funding + long/short + liquidações pra apontar o lado alavancado vulnerável. Comprados lotados pagando funding caro = risco de squeeze de BAIXA (são liquidados se o preço cai); vendidos lotados pagando = risco de squeeze de ALTA. Se as liquidações daquele lado já estão correndo, o squeeze está em curso.",
  liquidations: "Liquidações: posições alavancadas fechadas à força. Cascata de comprados empurra o preço pra baixo; de vendidos, pra cima.",
  institutionalBias: "Quem está no comando: institucional (Coinbase/spot) vs varejo (Binance/perps), via prêmio Coinbase, participação no volume e CVD agressor.",
  tvl: "TVL (Total Value Locked): valor total depositado nos protocolos DeFi da rede. Stablecoins entrando = capital novo chegando.",
  dexLiquidity: "Liquidez DEX: profundidade dos pares nas exchanges descentralizadas. Mais liquidez = mercado on-chain mais saudável e menos slippage.",
  macroMarket: "Dominância do BTC + capitalização total do mercado. Dominância subindo = dinheiro indo pro BTC (alts perdem força) e vice-versa.",
  rangePosition: "Onde o preço está dentro do range recente: 0% = fundo (discount/barato), 100% = topo (premium/caro). Mão forte tende a comprar no discount e vender no premium.",
  bias: "Viés da estrutura de mercado (Smart Money): de ALTA quando o preço rompe topos/fundos pra cima (BOS de alta), de BAIXA no contrário. Define a direção dominante.",
  oiDelta: "Delta de Open Interest vs preço (4h): mostra se o movimento veio de posições NOVAS. OI sobe + preço sobe = novas compras; OI sobe + preço cai = novas vendas (atenção a squeeze).",
  dvol: "DVOL — índice de volatilidade implícita da Deribit (o 'VIX da cripto'). Alto = o mercado espera movimentos grandes; baixo = calmaria precificada.",
  ivp: "IV Percentile 90d — onde a volatilidade implícita atual está na faixa dos últimos 90 dias (0–100). Alto = opções caras (favorece vender); baixo = baratas (favorece comprar).",
  ivRv: "IV − RV spread: volatilidade implícita menos a realizada. Positivo = mercado precificando mais oscilação do que de fato aconteceu — prêmio de risco caro.",
  termStructure: "Volatilidade implícita por prazo (7d→180d). Curto prazo acima do longo (backwardation) sugere o mercado precificando um evento próximo.",
  etfFlows: "Fluxo líquido dos ETFs spot (BTC/ETH) nos EUA — a porta institucional do ciclo. Entrada líquida = instituições comprando; saída = realizando. A sequência de dias mostra a persistência do fluxo.",
  marketLiquidity: "Liquidez do mercado: oferta total de stablecoins (o 'dry powder' parado pronto pra entrar) e TVL DeFi. Stablecoins subindo = combustível chegando; a dominância (stablecoins ÷ market cap) caindo = capital saindo pra risco.",
  optionsPositioning: "Posicionamento institucional em opções (Deribit): Put/Call ratio + skew de IV. Puts caros / muitos puts = demanda por proteção (defensivo); calls caros = aposta em alta.",
  cot: "COT (Commitment of Traders, CFTC): posicionamento SEMANAL por categoria nos futuros CME de BTC/ETH. Asset Managers = institucional 'real money' (direcional); Leveraged Funds = hedge funds (cujo net short costuma ser basis trade, não aposta de queda). Sai sexta, com dados de terça.",
  optionsFlow:
    "Proxy do HIRO (SpotGamma): estima pra que lado os dealers de opções empurram o preço ao se proteger (hedge). A cada 5 min soma o delta-fluxo — compra de call / venda de put = dealer compra à vista (fluxo +); venda de call / compra de put = vende (−) — e vai ACUMULANDO na janela. Linha colorida (eixo esquerdo) = esse fluxo, NÃO é preço: verde subindo = pressão compradora de hedge, vermelha caindo = vendedora. A pontilhada é o spot (eixo direito) — por isso as duas ficam em alturas diferentes, são escalas distintas. O que importa é comparar: andam juntas = hedge confirma o movimento; divergem (fluxo + mas preço caindo) = sinal de cautela.",
};
