import { useCallback, useEffect, useState } from "react";
import type { ReactNode } from "react";

import { useT } from "../lib/i18n";
import { supabase } from "../lib/supabase";
import type { Plan } from "../lib/types";

interface ReportRow {
  id: number;
  asset: string;
  model_used: string;
  content: string;
  created_at: string;
}

// ─── Markdown leve (sem dependência): títulos, negrito, listas ────────────────
function inline(s: string): ReactNode {
  return s.split(/(\*\*[^*]+\*\*)/g).map((p, i) =>
    p.startsWith("**") && p.endsWith("**") ? (
      <strong key={i} className="text-foreground">{p.slice(2, -2)}</strong>
    ) : (
      <span key={i}>{p}</span>
    ),
  );
}

function MarkdownLite({ text }: { text: string }) {
  const out: ReactNode[] = [];
  text.split("\n").forEach((line, i) => {
    const t = line.trim();
    if (!t) return out.push(<div key={i} className="h-2" />);
    if (t.startsWith("## ")) return out.push(<h4 key={i} className="mt-3 mb-1 text-sm font-semibold text-foreground">{inline(t.slice(3))}</h4>);
    if (t.startsWith("### ")) return out.push(<h5 key={i} className="mt-2 text-sm font-medium text-foreground">{inline(t.slice(4))}</h5>);
    if (t.startsWith("# ")) return out.push(<h4 key={i} className="mt-3 text-sm font-semibold text-foreground">{inline(t.slice(2))}</h4>);
    if (/^[-*]\s/.test(t)) return out.push(
      <div key={i} className="flex gap-1.5 text-sm leading-relaxed text-foreground"><span className="text-muted-foreground">•</span><span>{inline(t.slice(2))}</span></div>,
    );
    out.push(<p key={i} className="text-sm leading-relaxed text-foreground">{inline(t)}</p>);
  });
  return <div>{out}</div>;
}

/** Aba "Relatórios" — relatórios diários do ativo (broadcast, gerados por IA).
 *  Gating via RLS: Pro+ vê os últimos 14; Free vê só a vitrine (>7 dias). Botão de
 *  geração manual aparece só no Expert (cron/entrega ficam para etapa futura). */
export default function ReportsTab({ asset, plan, isExpert }: { asset: string; plan: Plan | null; isExpert: boolean }) {
  const { isEn } = useT();
  const tt = (pt: string, en: string) => (isEn ? en : pt);
  const advanced = plan?.advanced_metrics ?? false;
  const [rows, setRows] = useState<ReportRow[] | null>(null);
  const [open, setOpen] = useState<number | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (): Promise<ReportRow[]> => {
    const { data } = await supabase
      .from("ai_analysis")
      .select("id, asset, model_used, content, created_at")
      .eq("asset", asset)
      .eq("report_type", "daily")
      .order("created_at", { ascending: false })
      .limit(14);
    const list = (data as ReportRow[]) ?? [];
    setRows(list);
    return list;
  }, [asset]);

  useEffect(() => {
    setRows(null);
    setOpen(null);
    load();
  }, [load]);

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      const { data, error: fnErr } = await supabase.functions.invoke("cockpit-report", { body: { asset } });
      if (fnErr) {
        let msg = fnErr.message;
        const ctx = (fnErr as { context?: Response }).context;
        if (ctx && typeof ctx.json === "function") {
          const body = await ctx.json().catch(() => null);
          if (body?.error) msg = body.detail ? `${body.error} — ${body.detail}` : body.error;
        }
        throw new Error(msg);
      }
      const list = await load();
      if (list[0]) setOpen(list[0].id); // abre o recém-gerado
      void data;
    } catch (e) {
      setError(e instanceof Error ? e.message : tt("Falha ao gerar relatório", "Failed to generate report"));
    } finally {
      setGenerating(false);
    }
  }

  return (
    <section className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold text-foreground">{tt("Relatórios diários", "Daily reports")} · {asset}</h2>
          <p className="text-xs text-muted-foreground">{tt("Gerados pela IA a partir do snapshot, gamma, macro e notícias.", "Generated by AI from the snapshot, gamma, macro, and news.")}</p>
        </div>
        {isExpert && (
          <button
            onClick={generate}
            disabled={generating}
            className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
          >
            {generating ? tt("Gerando…", "Generating…") : tt("✨ Gerar relatório agora", "✨ Generate report now")}
          </button>
        )}
      </div>

      {!advanced && (
        <div className="rounded-xl border border-primary/40 bg-primary/10 p-4 text-sm text-foreground">
          {tt("🔒 Desbloqueie os ", "🔒 Unlock ")}<strong>{tt("relatórios diários", "daily reports")}</strong>{tt(" no plano ", " on the ")}<strong>Pro</strong>{tt(" — leitura completa do dia (gamma, fluxo, macro e cenários) gerada pela IA.", " — the full daily read (gamma, flow, macro, and scenarios) generated by AI.")}
        </div>
      )}

      {error && (
        <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-500/20 dark:bg-rose-500/10 dark:text-rose-400">{error}</div>
      )}

      {rows == null ? (
        <p className="text-sm text-muted-foreground">{tt("Carregando…", "Loading…")}</p>
      ) : rows.length === 0 ? (
        <div className="rounded-xl border border-border bg-card transition-all duration-200 hover:border-foreground/15 hover:shadow-card-hover dark:bg-card/60 p-6 text-sm text-muted-foreground">
          {advanced
            ? isExpert
              ? tt("Nenhum relatório ainda. Clique em “Gerar relatório agora”.", "No reports yet. Click “Generate report now”.")
              : tt("Nenhum relatório gerado ainda — em breve os relatórios diários aparecem aqui.", "No report generated yet — the daily reports will show up here soon.")
            : tt("Nenhum relatório de vitrine disponível ainda.", "No showcase report available yet.")}
        </div>
      ) : (
        <div className="space-y-2">
          {rows.map((r) => {
            const isOpen = open === r.id;
            const dt = new Date(r.created_at);
            return (
              <div key={r.id} className="rounded-xl border border-border bg-card transition-all duration-200 hover:border-foreground/15 hover:shadow-card-hover dark:bg-card/60">
                <button
                  onClick={() => setOpen(isOpen ? null : r.id)}
                  className="flex w-full items-center justify-between gap-3 p-4 text-left"
                >
                  <span className="flex items-center gap-2 text-sm text-foreground">
                    <span className="rounded bg-muted px-1.5 py-0.5 text-[10px] uppercase tracking-wide text-muted-foreground">{tt("Diário", "Daily")}</span>
                    <span className="num">{dt.toLocaleDateString(isEn ? "en-US" : "pt-BR")} · {dt.toLocaleTimeString(isEn ? "en-US" : "pt-BR", { hour: "2-digit", minute: "2-digit" })}</span>
                  </span>
                  <span className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span>{isOpen ? "−" : "+"}</span>
                  </span>
                </button>
                {isOpen && (
                  <div className="border-t border-border p-4">
                    <MarkdownLite text={r.content} />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
