import { useCallback, useEffect, useState } from "react";

import { useT } from "../lib/i18n";
import { supabase } from "../lib/supabase";
import type { Plan } from "../lib/types";
import Markdown from "./Markdown";

interface ReportRow {
  id: number;
  asset: string;
  model_used: string;
  content: string;
  created_at: string;
}

/** Aba "Relatórios" — relatórios diários do ativo (broadcast, gerados por IA).
 *  Gating via RLS: Pro+ vê os últimos 14; Free vê só a vitrine (>7 dias). Botão de
 *  geração manual aparece só no Expert (cron/entrega ficam para etapa futura). */
export default function ReportsTab({ asset, plan }: { asset: string; plan: Plan | null; isExpert?: boolean }) {
  const { isEn } = useT();
  const tt = (pt: string, en: string) => (isEn ? en : pt);
  const advanced = plan?.advanced_metrics ?? false;
  const [rows, setRows] = useState<ReportRow[] | null>(null);
  const [open, setOpen] = useState<number | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadErr, setLoadErr] = useState(false);
  const [copied, setCopied] = useState<number | null>(null);

  const load = useCallback(async (): Promise<ReportRow[]> => {
    // erro de rede != "sem relatorios": antes o error era ENGOLIDO e a UI mostrava o vazio.
    const { data, error: qErr } = await supabase
      .from("ai_analysis")
      .select("id, asset, model_used, content, created_at")
      .eq("asset", asset)
      .eq("report_type", "daily")
      .order("created_at", { ascending: false })
      .limit(14);
    if (qErr) {
      setLoadErr(true);
      setRows((prev) => prev ?? []); // sem dados anteriores -> lista vazia, mas com banner de erro
      return [];
    }
    setLoadErr(false);
    const list = (data as ReportRow[]) ?? [];
    setRows(list);
    return list;
  }, [asset]);

  useEffect(() => {
    setRows(null);
    setOpen(null);
    load();
  }, [load]);

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      const { data, error: fnErr } = await supabase.functions.invoke("cockpit-report", { body: { asset } });
      if (fnErr) {
        let msg = fnErr.message;
        const ctx = (fnErr as { context?: Response }).context;
        if (ctx && typeof ctx.json === "function") {
          const body = await ctx.json().catch(() => null);
          if (body?.error) msg = body.detail ? `${body.error} — ${body.detail}` : body.error;
        }
        throw new Error(msg);
      }
      const list = await load();
      if (list[0]) setOpen(list[0].id); // abre o recém-gerado
      void data;
    } catch (e) {
      setError(e instanceof Error ? e.message : tt("Falha ao gerar relatório", "Failed to generate report"));
    } finally {
      setGenerating(false);
    }
  }

  // Relatórios de IA só existem p/ os majors com dados completos (gamma/opções) — mesma
  // lista do cockpit-report. Nas demais moedas a aba era ENGANOSA ("em breve aparecem aqui",
  // nunca chegavam) e o botão devolvia 400 (auditoria 02/jul).
  const REPORT_ASSETS = ["BTC", "ETH", "SOL"];
  const supported = REPORT_ASSETS.includes(asset);

  return (
    <section className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold text-foreground">{tt("Relatórios diários", "Daily reports")} · {asset}</h2>
          <p className="text-xs text-muted-foreground">{tt("Gerados pela IA a partir do snapshot, gamma, macro e notícias.", "Generated by AI from the snapshot, gamma, macro, and news.")}</p>
        </div>
        {advanced && supported && (
          <button
            onClick={generate}
            disabled={generating}
            className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-50"
          >
            {generating ? tt("Gerando…", "Generating…") : tt("✨ Gerar relatório agora", "✨ Generate report now")}
          </button>
        )}
      </div>

      {!advanced && (
        <div className="rounded-xl border border-primary/40 bg-primary/10 p-4 text-sm text-foreground">
          {tt("🔒 Desbloqueie os ", "🔒 Unlock ")}<strong>{tt("relatórios diários", "daily reports")}</strong>{tt(" no plano ", " on the ")}<strong>Pro</strong>{tt(" — leitura completa do dia (gamma, fluxo, macro e cenários) gerada pela IA.", " — the full daily read (gamma, flow, macro, and scenarios) generated by AI.")}
        </div>
      )}

      {error && (
        <div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 dark:border-rose-500/20 dark:bg-rose-500/10 dark:text-rose-400">{error}</div>
      )}
      {loadErr && (
        <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-700 dark:text-amber-400">
          {tt("Não foi possível carregar os relatórios agora.", "Couldn't load the reports right now.")}{" "}
          <button onClick={() => load()} className="underline">{tt("Tentar de novo", "Try again")}</button>
        </div>
      )}

      {!supported ? (
        <div className="rounded-xl border border-border bg-card transition-all duration-200 hover:border-foreground/15 hover:shadow-card-hover dark:bg-card/60 p-6 text-sm text-muted-foreground">
          {tt(
            "Os relatórios diários por IA cobrem BTC, ETH e SOL (os ativos com dados completos de opções/gamma). Selecione um deles no topo para ler o relatório do dia.",
            "AI daily reports cover BTC, ETH, and SOL (the assets with full options/gamma data). Pick one of them at the top to read today's report.",
          )}
        </div>
      ) : rows == null ? (
        <div className="space-y-2">
          <div className="h-14 animate-pulse rounded-xl border border-border bg-card dark:bg-card/60" />
          <div className="h-14 animate-pulse rounded-xl border border-border bg-card dark:bg-card/60" />
        </div>
      ) : rows.length === 0 ? (
        <div className="rounded-xl border border-border bg-card transition-all duration-200 hover:border-foreground/15 hover:shadow-card-hover dark:bg-card/60 p-6 text-sm text-muted-foreground">
          {advanced
            ? tt("Nenhum relatório ainda hoje — o diário sai automático às ~08:00 (BRT), com repescagem ao meio-dia. Você também pode clicar em “Gerar relatório agora”.", "No report yet today — the daily goes out automatically at ~08:00 BRT (11:00 UTC), with a noon retry. You can also click “Generate report now”.")
            : tt("Nenhum relatório de vitrine disponível ainda (o Free lê os relatórios com mais de 7 dias).", "No showcase report available yet (Free reads reports older than 7 days).")}
        </div>
      ) : (
        <div className="space-y-2">
          {rows.map((r) => {
            const isOpen = open === r.id;
            const dt = new Date(r.created_at);
            // Previa: primeira linha "de texto" do relatorio (pula titulos/listas) — da pra
            // escolher qual abrir sem expandir um por um.
            const preview = r.content
              .split("\n")
              .map((l) => l.trim())
              .find((l) => l && !l.startsWith("#") && !/^[-*]\s/.test(l))
              ?.replace(/\*\*/g, "")
              .slice(0, 140);
            const flash = (r.model_used ?? "").includes("flash");
            return (
              <div key={r.id} className="rounded-xl border border-border bg-card transition-all duration-200 hover:border-foreground/15 hover:shadow-card-hover dark:bg-card/60">
                <button
                  onClick={() => setOpen(isOpen ? null : r.id)}
                  className="flex w-full items-center justify-between gap-3 p-4 text-left"
                >
                  <span className="min-w-0 flex-1 text-sm text-foreground">
                    <span className="flex items-center gap-2">
                      <span className="num font-medium">{dt.toLocaleDateString(isEn ? "en-US" : "pt-BR")} · {dt.toLocaleTimeString(isEn ? "en-US" : "pt-BR", { hour: "2-digit", minute: "2-digit" })}</span>
                      <span
                        className={`rounded px-1.5 py-0.5 text-[9px] uppercase tracking-wide ${flash ? "bg-muted text-muted-foreground" : "bg-primary/15 text-primary"}`}
                        title={flash ? tt("Gerado pelo modelo rápido (flash)", "Generated by the fast model (flash)") : tt("Gerado pelo modelo mais capaz (pro)", "Generated by the most capable model (pro)")}
                      >
                        {flash ? "⚡ flash" : "🧠 pro"}
                      </span>
                    </span>
                    {!isOpen && preview && <span className="mt-0.5 block truncate text-xs text-muted-foreground">{preview}…</span>}
                  </span>
                  <span className="flex shrink-0 items-center gap-2 text-xs text-muted-foreground">
                    <span>{isOpen ? "−" : "+"}</span>
                  </span>
                </button>
                {isOpen && (
                  <div className="border-t border-border p-4">
                    <div className="mb-2 flex justify-end">
                      <button
                        onClick={() => {
                          navigator.clipboard?.writeText(r.content).then(() => {
                            setCopied(r.id);
                            setTimeout(() => setCopied((c) => (c === r.id ? null : c)), 2000);
                          });
                        }}
                        className="rounded-md border border-border px-2 py-1 text-[11px] text-muted-foreground hover:bg-muted hover:text-foreground"
                      >
                        {copied === r.id ? tt("✓ Copiado", "✓ Copied") : tt("Copiar relatório", "Copy report")}
                      </button>
                    </div>
                    <Markdown text={r.content} />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </section>
  );
}
